services:
  # Nginx Web Server
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - app-network

  # PHP-FPM 7.4
  php:
    image: php:7.4.33-fpm
    container_name: php_fpm
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    command: >
      bash -c "
      docker-php-ext-install pdo pdo_mysql &&
      php-fpm
      "

  # MySQL 8.0
  mysql:
    image: mysql:8.0.43
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin (資料庫管理工具)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    networks:
      - app-network

# 網路設定
networks:
  app-network:
    driver: bridge

# 持久化資料卷
volumes:
  mysql_data:
    driver: local